//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryBlog_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Columns
    {
        public int ID { get; set; }
        public string adCompany { get; set; }
        public string adCompanyTel { get; set; }
        public string adPhoto { get; set; }
        public string adURL { get; set; }
        public string adRemarks { get; set; }
        public System.DateTime adCreateTime { get; set; }
    }
}
