//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryBlog_WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoryBlog_DBEntities : DbContext
    {
        public StoryBlog_DBEntities()
            : base("name=StoryBlog_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AD_Columns> AD_Columns { get; set; }
        public virtual DbSet<Administration> Administration { get; set; }
        public virtual DbSet<ArtComment> ArtComment { get; set; }
        public virtual DbSet<ArticleClass> ArticleClass { get; set; }
        public virtual DbSet<ArticleInfo> ArticleInfo { get; set; }
        public virtual DbSet<AttentionInfo> AttentionInfo { get; set; }
        public virtual DbSet<PicComment> PicComment { get; set; }
        public virtual DbSet<PictureClass> PictureClass { get; set; }
        public virtual DbSet<PictureInfo> PictureInfo { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
