//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryBlog_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PictureClass()
        {
            this.PictureInfo = new HashSet<PictureInfo>();
        }
    
        public int ID { get; set; }
        public string picClsTitle { get; set; }
        public string CoverFile { get; set; }
        public string uAccount { get; set; }
        public int picClsAuthority { get; set; }
        public string picClsDescribe { get; set; }
        public int picClsPicCnt { get; set; }
        public System.DateTime picClsCreateTime { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PictureInfo> PictureInfo { get; set; }
    }
}
