//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryBlog_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PictureInfo()
        {
            this.PicComment = new HashSet<PicComment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ImgFile { get; set; }
        public Nullable<System.DateTime> picCreateTime { get; set; }
        public Nullable<int> picHot { get; set; }
        public int PicClsID { get; set; }
        public string uAccount { get; set; }
        public string picDescribe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PicComment> PicComment { get; set; }
        public virtual PictureClass PictureClass { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
